"""Added row and column count fields to dataset

Revision ID: 2ffbf8c1c97e
Revises: 28f978306262
Create Date: 2025-03-06 17:42:44.181445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffbf8c1c97e'
down_revision: Union[str, None] = '28f978306262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('column_count', sa.Integer(), nullable=True))
    op.alter_column('datasets', 'votes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'votes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('datasets', 'column_count')
    op.drop_column('datasets', 'row_count')
    # ### end Alembic commands ###
